<<<<<<< HEAD
import type React from "react"
import type { Metadata } from "next"

import "./globals.css"
import ClientLayout from "./clientLayout"
=======
import type React from "react";
import type { Metadata } from "next";

import "./globals.css";
import ClientLayout from "./clientLayout";
>>>>>>> supplier

export const metadata: Metadata = {
  title: "Sustain Pro",
  description: "Generated by create next app",
<<<<<<< HEAD
    generator: 'v0.dev',
    icons: {
    icon: "/sustainPro_logo.png", // relative to /public folder
  },
}
=======
  generator: "v0.dev",
  icons: {
    icon: "/sustainPro_logo.png",
  },
};
>>>>>>> supplier

export default function RootLayout({
  children,
}: {
<<<<<<< HEAD
  children: React.ReactNode
}) {
  return <ClientLayout>{children}</ClientLayout>
=======
  children: React.ReactNode;
}) {
  return <ClientLayout>{children}</ClientLayout>;
>>>>>>> supplier
}
